//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPokerCardCatcher.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPPokerCardCatcher.Common.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://drivehud.com/product/pm-hud.
        /// </summary>
        internal static string Common_BuyLink {
            get {
                return ResourceManager.GetString("Common_BuyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong! Please contact support if this error happens again..
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: PPPoker Card Catcher will be closed.
        /// </summary>
        internal static string Common_FatalError {
            get {
                return ResourceManager.GetString("Common_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License:.
        /// </summary>
        internal static string Common_License {
            get {
                return ResourceManager.GetString("Common_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_NotificationView_Cancel {
            get {
                return ResourceManager.GetString("Common_NotificationView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Common_NotificationView_No {
            get {
                return ResourceManager.GetString("Common_NotificationView_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_NotificationView_OK {
            get {
                return ResourceManager.GetString("Common_NotificationView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Common_NotificationView_Yes {
            get {
                return ResourceManager.GetString("Common_NotificationView_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Manual.
        /// </summary>
        internal static string Common_OnlineManual {
            get {
                return ResourceManager.GetString("Common_OnlineManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Common_Registration {
            get {
                return ResourceManager.GetString("Common_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Common_RegistrationView_Activate {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Common_RegistrationView_Back {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Common_RegistrationView_Buy {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_RegistrationView_Cancel {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not activate license. Please try again or contact support..
        /// </summary>
        internal static string Common_RegistrationView_CouldNotBeActivated {
            get {
                return ResourceManager.GetString("Common_RegistrationView_CouldNotBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day(s) left:.
        /// </summary>
        internal static string Common_RegistrationView_DaysLeft {
            get {
                return ResourceManager.GetString("Common_RegistrationView_DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string Common_RegistrationView_Email {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string Common_RegistrationView_ExpiredSerialSplitter {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiredSerialSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license(s) has expired ({0}). Please renew..
        /// </summary>
        internal static string Common_RegistrationView_ExpiredText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} day(s) left.
        /// </summary>
        internal static string Common_RegistrationView_ExpiringLicenseTitle {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiringLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license(s) are expiring soon. Please renew..
        /// </summary>
        internal static string Common_RegistrationView_ExpiringSoonText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_ExpiringSoonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher
        ///The PPPoker Card Catcher is an add-on application that will allow you to capture and run a HUD through DriveHUD/HM2/HM3/PT4. It includes a fully functional 7 day trial. Click Try to enable the trial..
        /// </summary>
        internal static string Common_RegistrationView_GreetingText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register software. Invalid serial number. Please enter valid serial or contact support..
        /// </summary>
        internal static string Common_RegistrationView_InvalidSerial {
            get {
                return ResourceManager.GetString("Common_RegistrationView_InvalidSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t register software. Unexpected error occured. Please contact support..
        /// </summary>
        internal static string Common_RegistrationView_LicenseError {
            get {
                return ResourceManager.GetString("Common_RegistrationView_LicenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to license server. Please check your internet connection..
        /// </summary>
        internal static string Common_RegistrationView_NoConnection {
            get {
                return ResourceManager.GetString("Common_RegistrationView_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_RegistrationView_OK {
            get {
                return ResourceManager.GetString("Common_RegistrationView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Common_RegistrationView_Register {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following data to register your version of PPPoker Card Catcher:.
        /// </summary>
        internal static string Common_RegistrationView_RegisterText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        internal static string Common_RegistrationView_Renew {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial:.
        /// </summary>
        internal static string Common_RegistrationView_Serial {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. PPPoker Card Catcher has been successfully registered!.
        /// </summary>
        internal static string Common_RegistrationView_SuccessText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher Registration.
        /// </summary>
        internal static string Common_RegistrationView_Title {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string Common_RegistrationView_Trial {
            get {
                return ResourceManager.GetString("Common_RegistrationView_Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You trial period is over. Please register your version of PPPoker Card Catcher.
        /// </summary>
        internal static string Common_RegistrationView_TrialExpiredText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TrialExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register error. Internal error occurred. Please contact support..
        /// </summary>
        internal static string Common_RegistrationView_TrialRegisterError {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TrialRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the following data to activate your trial period:.
        /// </summary>
        internal static string Common_RegistrationView_TrialRegisterText {
            get {
                return ResourceManager.GetString("Common_RegistrationView_TrialRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced logging.
        /// </summary>
        internal static string Common_Settings_AdvancedLogging {
            get {
                return ResourceManager.GetString("Common_Settings_AdvancedLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Common_Settings_Apply {
            get {
                return ResourceManager.GetString("Common_Settings_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic updates.
        /// </summary>
        internal static string Common_Settings_AutomaticUpdating {
            get {
                return ResourceManager.GetString("Common_Settings_AutomaticUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Settings_Cancel {
            get {
                return ResourceManager.GetString("Common_Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher Settings.
        /// </summary>
        internal static string Common_Settings_Title {
            get {
                return ResourceManager.GetString("Common_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace:.
        /// </summary>
        internal static string Common_StackTrace {
            get {
                return ResourceManager.GetString("Common_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START CATCHER.
        /// </summary>
        internal static string Common_StartCatcher {
            get {
                return ResourceManager.GetString("Common_StartCatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP CATCHER.
        /// </summary>
        internal static string Common_StopCatcher {
            get {
                return ResourceManager.GetString("Common_StopCatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher.
        /// </summary>
        internal static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string Common_Troubleshoot {
            get {
                return ResourceManager.GetString("Common_Troubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_UpdateView_Cancel {
            get {
                return ResourceManager.GetString("Common_UpdateView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string Common_UpdateView_Completed {
            get {
                return ResourceManager.GetString("Common_UpdateView_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher v.{0} is available.
        /// </summary>
        internal static string Common_UpdateView_Header {
            get {
                return ResourceManager.GetString("Common_UpdateView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes (v.{0}):.
        /// </summary>
        internal static string Common_UpdateView_ReleaseNotes {
            get {
                return ResourceManager.GetString("Common_UpdateView_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher Update Notice.
        /// </summary>
        internal static string Common_UpdateView_Title {
            get {
                return ResourceManager.GetString("Common_UpdateView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Common_UpdateView_Update {
            get {
                return ResourceManager.GetString("Common_UpdateView_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Upgrade ].
        /// </summary>
        internal static string Common_Upgrade {
            get {
                return ResourceManager.GetString("Common_Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.{0} (beta).
        /// </summary>
        internal static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
    }
}
