//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPokerCardCatcher.Bootstrapper.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPPokerCardCatcher.Bootstrapper.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation is already in progress..
        /// </summary>
        public static string Common_CancelAlreadyInProgressMessageBoxBody {
            get {
                return ResourceManager.GetString("Common_CancelAlreadyInProgressMessageBoxBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher Setup.
        /// </summary>
        public static string Common_CancelAlreadyInProgressMessageBoxTitle {
            get {
                return ResourceManager.GetString("Common_CancelAlreadyInProgressMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the installation?.
        /// </summary>
        public static string Common_CancelDialogBody {
            get {
                return ResourceManager.GetString("Common_CancelDialogBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher Setup.
        /// </summary>
        public static string Common_CancelDialogTitle {
            get {
                return ResourceManager.GetString("Common_CancelDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string Common_ExitMessage_Text {
            get {
                return ResourceManager.GetString("Common_ExitMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        public static string Common_ExitMessage_Title {
            get {
                return ResourceManager.GetString("Common_ExitMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation was cancelled..
        /// </summary>
        public static string Common_FinishErrorView_FinishErrorCanceled {
            get {
                return ResourceManager.GetString("Common_FinishErrorView_FinishErrorCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, status code: 0x{0:X8}.
        /// </summary>
        public static string Common_FinishErrorView_FinishErrorUnknown {
            get {
                return ResourceManager.GetString("Common_FinishErrorView_FinishErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Common_FinishView_Close {
            get {
                return ResourceManager.GetString("Common_FinishView_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Common_FinishView_Launch {
            get {
                return ResourceManager.GetString("Common_FinishView_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher was succesfully installed. 
        ///Thank you for using PPPoker Card Catcher!.
        /// </summary>
        public static string Common_FinishView_ThankYouText {
            get {
                return ResourceManager.GetString("Common_FinishView_ThankYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher was successfully uninstalled. .
        /// </summary>
        public static string Common_FinishView_UninstallText {
            get {
                return ResourceManager.GetString("Common_FinishView_UninstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Error while installing.
        /// </summary>
        public static string Common_InstallErrorMessageTitle {
            get {
                return ResourceManager.GetString("Common_InstallErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Common_InstallView_Browse {
            get {
                return ResourceManager.GetString("Common_InstallView_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_InstallView_Cancel {
            get {
                return ResourceManager.GetString("Common_InstallView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create desktop shortcut.
        /// </summary>
        public static string Common_InstallView_CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("Common_InstallView_CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcut in start menu.
        /// </summary>
        public static string Common_InstallView_CreateProgramMenuShortcut {
            get {
                return ResourceManager.GetString("Common_InstallView_CreateProgramMenuShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Location:.
        /// </summary>
        public static string Common_InstallView_DestinationLocation {
            get {
                return ResourceManager.GetString("Common_InstallView_DestinationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Common_InstallView_Install {
            get {
                return ResourceManager.GetString("Common_InstallView_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will install PPPoker Card Catcher on your computer.
        ///It is recommended that you close all other applications before continuing.
        ///Click Install to continue or Cancel to exit Setup..
        /// </summary>
        public static string Common_InstallView_WelcomeText {
            get {
                return ResourceManager.GetString("Common_InstallView_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the PPPoker Card Catcher Setup.
        /// </summary>
        public static string Common_InstallView_WelcomeTitle {
            get {
                return ResourceManager.GetString("Common_InstallView_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_MaintenanceView_Cancel {
            get {
                return ResourceManager.GetString("Common_MaintenanceView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Common_MaintenanceView_Uninstall {
            get {
                return ResourceManager.GetString("Common_MaintenanceView_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher is arelady installed..
        /// </summary>
        public static string Common_MaintenanceView_WelcomeText {
            get {
                return ResourceManager.GetString("Common_MaintenanceView_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the PPPoker Card Catcher Setup.
        /// </summary>
        public static string Common_MaintenanceView_WelcomeTitle {
            get {
                return ResourceManager.GetString("Common_MaintenanceView_WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of {0} is already installed.
        /// </summary>
        public static string Common_NewerVersionInstalledMessage {
            get {
                return ResourceManager.GetString("Common_NewerVersionInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Newer version already installed.
        /// </summary>
        public static string Common_NewerVersionInstalledTitle {
            get {
                return ResourceManager.GetString("Common_NewerVersionInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_NotificationView_Cancel {
            get {
                return ResourceManager.GetString("Common_NotificationView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_NotificationView_No {
            get {
                return ResourceManager.GetString("Common_NotificationView_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_NotificationView_OK {
            get {
                return ResourceManager.GetString("Common_NotificationView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_NotificationView_Yes {
            get {
                return ResourceManager.GetString("Common_NotificationView_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Common_PlanView_InstallAction {
            get {
                return ResourceManager.GetString("Common_PlanView_InstallAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while setup installs PPPoker Card Catcher on your computer. This may take a few minutes.
        /// </summary>
        public static string Common_PlanView_InstallActionDescription {
            get {
                return ResourceManager.GetString("Common_PlanView_InstallActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning installation of {0}....
        /// </summary>
        public static string Common_PlanView_Text {
            get {
                return ResourceManager.GetString("Common_PlanView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        public static string Common_PlanView_UninstallAction {
            get {
                return ResourceManager.GetString("Common_PlanView_UninstallAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while setup uninstalls PPPoker Card Catcher from your computer. This may take a few minutes.
        /// </summary>
        public static string Common_PlanView_UninstallActionDescription {
            get {
                return ResourceManager.GetString("Common_PlanView_UninstallActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPPoker Card Catcher Setup.
        /// </summary>
        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.{0}.
        /// </summary>
        public static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
    }
}
